---
title: "weighting_jg"
author: "JGaun"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message= FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)

#packages for survey analysis
library(haven)
library(anesrake)
library(weights)
library(survey)
library(srvyr)
library(jtools)
library(remotes)
```

```{r create pop and sample margins}
#load data 
survey <- read_csv(here("data", "survey_data_tidy_sbv_filtered.csv"))

#set targets
target <- read.csv(here("data","census", "population_margins.csv")) %>% 
  clean_names() %>% 
  select(sex, age_group, proportion)


#calculate sample margins
sample_margin <- survey

sample_margin$q31 <- as.integer(sample_margin$q31)

#create bins for age
labs <- c(paste(seq(0, 95, by = 5), seq(0 + 5 - 1, 100 - 1, by = 5),
                sep = "-"), paste(100, "+", sep = ""))

sample_margin<- sample_margin%>% 
  mutate(age= 2022- q31) 

sample_margin$age_group <- cut(sample_margin$age, breaks = c(seq(0, 100, by = 5), Inf), labels = labs, right = FALSE)

sample_margin <- sample_margin %>% 
  mutate(age_group = case_when(
    age_group == "85-89" ~ "85+",
    age_group == "90-94" ~ "85+",
    age_group == "95-99" ~ "85+",
    TRUE ~ as.character (age_group))) %>% 
  select(q32, age_group) %>% 
  drop_na()

colnames(sample_margin) <- c("sex", "age_group")
  
sample_margin <- sample_margin %>% 
  mutate(sex = case_when(
    sex == "Woman" ~ "female",
    sex == "Man" ~ "male",
    sex == "non-binary"~ "NA")) %>% 
  filter(sex != "NA") %>% 
  filter(age_group != "5-9") %>% 
  group_by(sex, age_group) %>% 
  summarize(count = n()) %>% 
  mutate(proportion = (count / sum(count))) 

#write.csv(sample_margin, here("data", "census", "sample_margin.csv"))

#the sample margin length must match the population margin so I exported the csv with all this work and manaually manipulated it in Excel to make sure it matched.  I reloaded the data in as a new csv "sample_margins_2.csv" that perfectly matches the population margins 'target' dataframe

sample_margin <- read_csv(here("data", "census", "sample_margin_2.csv"))
```


```{r create age group categories in the survey data}
survey$q31 <- as.integer(survey$q31)

#create bins for age
labs <- c(paste(seq(0, 95, by = 5), seq(0 + 5 - 1, 100 - 1, by = 5),
                sep = "-"), paste(100, "+", sep = ""))

survey<- survey %>% 
  mutate(age= 2022- q31) 

survey$age_group <- cut(survey$age, breaks = c(seq(0, 100, by = 5), Inf), labels = labs, right = FALSE)

survey<- survey%>% 
  mutate(age_group = case_when(
    age_group == "85-89" ~ "85+",
    age_group == "90-94" ~ "85+",
    age_group == "95-99" ~ "85+",
    TRUE ~ as.character (age_group))) %>% 
    mutate(sex = case_when(
    q32 == "Woman" ~ "female",
    q32 == "Man" ~ "male",
    q32 == "non-binary"~ "NA")) %>% 
  filter(sex != "NA") %>% 
  filter(age_group != "5-9") 
  
```


```{r weighting}
sample_margin <- sample_margin %>% 
  filter(age_group != "0-4",
         age_group != "9-May",
         age_group != "14-Oct")
target <- target %>% 
    filter(age_group != "0-4",
         age_group != "9-May",
         age_group != "14-Oct")

weighted <- rake(survey, sample.margins = sample_margin, population.margins = target)
```















